# Generated by Django 2.1 on 2018-11-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
                ('tipo_movimiento', models.CharField(choices=[('Deposito', 'Depósito'), ('Solicitud', 'Solicitud'), ('Registro', 'Registro')], max_length=10)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitud.Solicitud')),
                ('usuario_emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioEmisor', to='usuario.Usuario')),
                ('usuario_receptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioReceptor', to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion_backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_backup', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_backup', models.DateTimeField(auto_now=True)),
                ('estado_backup', models.IntegerField(default=1)),
                ('tipo_movimiento_backup', models.CharField(choices=[('retiro', 'Retiro'), ('deposito', 'Depósito')], max_length=8)),
                ('solicitud_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitud.Solicitud')),
                ('usuario_emisor_backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioEmisorBackup', to='usuario.Usuario')),
                ('usuario_receptor_backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioReceptorBackup', to='usuario.Usuario')),
            ],
        ),
    ]
