# Generated by Django 2.1 on 2018-10-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='tipo_movimiento',
            field=models.CharField(choices=[('retiro', 'Retiro'), ('deposito', 'Depósito')], max_length=10),
        ),
    ]
