# Generated by Django 2.1 on 2018-08-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20180827_1053'),
        ('solicitud', '0001_initial'),
        ('deposito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('tipo_movimiento', models.CharField(choices=[('retiro', 'Retiro'), ('deposito', 'Depósito')], max_length=8)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitud.Solicitud')),
                ('usuario_emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioEmisor', to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion_backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_backup', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_backup', models.DateTimeField(auto_now=True)),
                ('estado_backup', models.BooleanField(default=True)),
                ('tipo_movimiento_backup', models.CharField(choices=[('retiro', 'Retiro'), ('deposito', 'Depósito')], max_length=8)),
                ('solicitud_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitud.Solicitud')),
                ('usuario_emisor_backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioEmisorBackup', to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deposito.Operacion')),
                ('usuario_receptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioReceptor', to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion_Usuario_backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion_backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deposito.Operacion')),
                ('usuario_receptor_backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioReceptorBackup', to='usuario.Usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='operaciones',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='operaciones',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='operaciones',
            name='usuario_asignado',
        ),
        migrations.RemoveField(
            model_name='operacionesbackup',
            name='solicitud_backup',
        ),
        migrations.RemoveField(
            model_name='operacionesbackup',
            name='usuario_asignado_backup',
        ),
        migrations.RemoveField(
            model_name='operacionesbackup',
            name='usuario_backup',
        ),
        migrations.DeleteModel(
            name='Operaciones',
        ),
        migrations.DeleteModel(
            name='OperacionesBackUp',
        ),
    ]
