# Generated by Django 2.1 on 2018-08-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposito', '0001_initial'),
        ('solicitud', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.Solicitud'),
        ),
        migrations.AddField(
            model_name='deposito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Usuario'),
        ),
    ]
