# Generated by Django 2.1 on 2018-10-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0002_auto_20181009_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='estado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='operacion_backup',
            name='estado_backup',
            field=models.IntegerField(),
        ),
    ]
