# Generated by Django 2.1 on 2018-08-29 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_saldo_fecha_modificacion'),
        ('deposito', '0002_auto_20180827_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion_usuario',
            name='operacion',
        ),
        migrations.RemoveField(
            model_name='operacion_usuario',
            name='usuario_receptor',
        ),
        migrations.RemoveField(
            model_name='operacion_usuario_backup',
            name='operacion_backup',
        ),
        migrations.RemoveField(
            model_name='operacion_usuario_backup',
            name='usuario_receptor_backup',
        ),
        migrations.AddField(
            model_name='operacion',
            name='saldo_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacion',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacion',
            name='usuario_receptor',
            field=models.ForeignKey(default=12312312, on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioReceptor', to='usuario.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacion_backup',
            name='usuario_receptor_backup',
            field=models.ForeignKey(default=12312312, on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioReceptorBackup', to='usuario.Usuario'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Operacion_Usuario',
        ),
        migrations.DeleteModel(
            name='Operacion_Usuario_backup',
        ),
    ]
