# Generated by Django 2.1 on 2018-10-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0004_auto_20181009_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
