# Generated by Django 2.1 on 2018-10-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0005_auto_20181010_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Deposito', 'Depósito'), ('Solicitud', 'Solicitud'), ('Registro', 'Registro')], max_length=10),
        ),
    ]
