# Generated by Django 2.1 on 2018-08-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
