# Generated by Django 2.1 on 2018-09-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0003_auto_20180830_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='monto_completado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
