# Generated by Django 2.1 on 2018-09-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0004_solicitud_monto_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='monto_faltante',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
