# Generated by Django 2.1 on 2018-11-15 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad_bancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='entidades_bancarias')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=50)),
                ('fecha_redaccion', models.DateTimeField(auto_now_add=True)),
                ('texto_mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('foto_perfil', models.ImageField(blank=True, default='usuario/Koala.jpg', upload_to='usuario')),
                ('numero_cuenta', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('depositos_pendientes', models.IntegerField(default=1, null=True)),
                ('dni_referido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.Usuario')),
                ('entidad_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Entidad_bancaria')),
                ('usuario_login', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='saldo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='mensaje_usuario',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptor', to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emisor', to='usuario.Usuario'),
        ),
    ]
