# Generated by Django 2.1 on 2018-10-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_depositos_pendientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='depositos_pendientes',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
