# Generated by Django 2.1 on 2018-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20181011_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
