# Generated by Django 2.1 on 2018-11-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_receptor', models.IntegerField()),
                ('usuario_sesion', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('monto', models.IntegerField()),
                ('confirmado', models.IntegerField()),
                ('id_emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Usuario')),
            ],
        ),
    ]
