# Generated by Django 2.1 on 2018-10-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacion', '0002_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='monto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
