# Generated by Django 2.1 on 2018-10-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacion', '0003_notificacion_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='confirmado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
