# Generated by Django 2.1 on 2018-10-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_saldo_fecha_modificacion'),
        ('notificacion', '0004_notificacion_confirmado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion_depositar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('monto', models.IntegerField()),
                ('confirmado', models.IntegerField()),
                ('usuario_receptor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Usuario')),
            ],
        ),
    ]
