# Generated by Django 2.1 on 2018-10-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacion', '0005_notificacion_depositar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion_depositar',
            old_name='usuario_receptor_id',
            new_name='receptor',
        ),
    ]
