# Generated by Django 2.1 on 2018-10-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacion', '0006_auto_20181001_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='usuario_sesion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
