# Generated by Django 2.1 on 2018-11-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscripcion', models.IntegerField()),
                ('monto_minimo', models.IntegerField()),
                ('enlace_youtube', models.CharField(max_length=600)),
                ('horas_plazo_deposito', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tasa_interes', models.IntegerField()),
            ],
        ),
    ]
