# Generated by Django 2.1 on 2018-10-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='monto_minimo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
