# Generated by Django 2.1 on 2018-10-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_general_monto_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='horas_plazo_deposito',
            field=models.IntegerField(default=48),
            preserve_default=False,
        ),
    ]
