# Generated by Django 2.1 on 2018-10-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_general_horas_plazo_deposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tasa_interes', models.IntegerField()),
            ],
        ),
    ]
