# Generated by Django 2.1 on 2018-08-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fragmento', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=2000)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
    ]
