# Generated by Django 2.1 on 2018-08-31 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Art',
            new_name='Articulo',
        ),
    ]
