# Generated by Django 2.1 on 2018-10-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0003_auto_20180928_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fragmento',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
