# Generated by Django 2.1 on 2018-10-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0004_auto_20181004_0329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='articulo',
            name='fragmento',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
