# Generated by Django 2.1 on 2018-10-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0006_auto_20181004_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='categoria',
        ),
    ]
