# Generated by Django 2.1 on 2018-10-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0007_remove_articulo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='articulo.Categoria'),
            preserve_default=False,
        ),
    ]
