# Generated by Django 2.1 on 2018-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonio', '0002_auto_20180822_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
