# Generated by Django 2.1 on 2018-09-28 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testimonio', '0005_auto_20180822_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
