# Generated by Django 2.1 on 2018-11-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('deposito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('monto_actual', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fecha_actual', models.DateField(auto_now=True, null=True)),
                ('confirmado', models.IntegerField()),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deposito.Operacion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.Usuario')),
            ],
        ),
    ]
