# Generated by Django 2.1 on 2018-10-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposito', '0006_auto_20181018_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actual', models.DateTimeField(auto_now=True)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deposito.Operacion')),
            ],
        ),
    ]
