# Generated by Django 2.1 on 2018-10-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0006_auto_20181018_1431'),
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='General',
            new_name='Pago',
        ),
    ]
