# Generated by Django 2.1 on 2018-11-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='ganancia_referente',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
