# Generated by Django 2.1 on 2018-10-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_auto_20181020_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_actual',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_actual',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
