# Generated by Django 2.1 on 2018-11-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_pago_ganancia_referente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='confirmado_referente',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
