# Generated by Django 2.1 on 2018-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0003_pago_confirmado_referente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tasa_interes_referente',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
