# Generated by Django 2.1 on 2018-10-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0004_pago_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='confirmado',
            field=models.IntegerField(default=0),
        ),
    ]
