# Generated by Django 2.1 on 2018-11-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0004_pago_tasa_interes_referente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='ganancia_referido',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
