# Generated by Django 2.1 on 2018-10-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0005_pago_confirmado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='confirmado',
            field=models.IntegerField(),
        ),
    ]
